"""Cardio MIRAI AI Heart Age -- ARCHITECTURE/SCHEMA ONLY.

No score is computed here. This module exists solely to document the
intended future input schema so later work has a stable target to build
toward -- it must not be mistaken for a working model.

Future concept:
    Clinical + ECG + Echocardiography
        -> Cardio MIRAI Multimodal Model (not yet built)
        -> Cardio MIRAI Heart Age
        -> Heart Age Gap

Explicitly excluded from ever being wired into this as inputs, per instructions:
  - The hardcoded/placeholder p_axis_deg from the legacy ECG pipeline
    (cardiomirai/api.py's _p_axis_deg) -- it is a constant, not a measurement.
  - The legacy formula-based _qtc_ms (feeds the PTB-XL atrial model only;
    see docs/qt_qtc_root_cause.md for why it must not be reused elsewhere).
  - The unresolved legacy PTB-XL atrial-abnormality score (see
    docs/ptbxl_model_provenance_audit.md -- target provenance UNRESOLVED).

BMI is deliberately absent from the Evidence-Based Cardiovascular Risk
calculator (the Total CVD PREVENT equation's BMI coefficients are zero),
but is preserved here as a placeholder field: it may be relevant to a
future heart-failure-specific or multimodal model, which is a materially
different, not-yet-built calculation.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class FutureHeartAgeInputSchema:
    """Placeholder schema. No field here is populated by any working model yet."""

    # Clinical
    chronological_age_years: float | None = None
    sex: str | None = None
    bmi_kg_m2: float | None = None  # NOT used by the PREVENT-based calculator; reserved for future HF/multimodal work
    blood_pressure_systolic_mmhg: float | None = None
    diabetes_status: bool | None = None
    smoking_status: bool | None = None

    # ECG (from ECG Core, once genuinely validated for this purpose)
    ecg_heart_rate_bpm: float | None = None
    ecg_pr_interval_ms: float | None = None
    ecg_qrs_duration_ms: float | None = None
    ecg_qtc_ms: float | None = None  # from the CLINICAL delineation path only, never the legacy formula
    ecg_current_af_evidence_category: str | None = None

    # Echocardiography (not yet integrated anywhere in Cardio MIRAI)
    echo_lv_ejection_fraction_percent: float | None = None
    echo_left_atrial_volume_index: float | None = None
    echo_diastolic_function_grade: str | None = None


STATUS = "Research model under development"
NOTE = "No AI Heart Age number is generated by this schema. It exists to document intended future inputs only."
